# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 333eab00d1375d70c2731e69316ddb34aa4b060ccabfe717fab052515b77bd7c12fdef0afeccbdd54fa32f825885c870a8af5d253b1e28bc176228ff20613137

test:
  secret_key_base: 46940cf096949659bfef9c783b7342b6ba5ef133005837fecdbcf90bbc1839a0e89f08383ba6b9c9ee5f8c33ced0192f6554765d9dd889f82cd71342aa271128

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
